CREATE DATABASE isup;
\c isup;


CREATE TABLE users (
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) PRIMARY KEY NOT NULL UNIQUE,
  password VARCHAR(64) NOT NULL,
  tos_agreement BOOLEAN NOT NULL DEFAULT FALSE,
  date_created DATE
);


CREATE TABLE tokens (
  email VARCHAR(255) NOT NULL REFERENCES users(email) ON DELETE CASCADE,
  id VARCHAR(255) PRIMARY KEY NOT NULL UNIQUE,
  expires TIMESTAMP NOT NULL
);


\dt